name: 'Baidu Tieba Auto Sign'

on:
  push:
    branches:
      - main
  schedule:
    - cron: 17 11,20 * * *

jobs:
  tieba_sign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v3
      - name: 'Set python'
        uses: actions/setup-python@v1
      - name: 'Install dependencies'
        run: python -m pip install --upgrade requests lxml cssselect
      - name: 'Start Sign'
        env:
          BDUSS: ${{ secrets.BDUSS }}
          HOST: ${{ secrets.HOST }}
          FROM: ${{ secrets.FROM }}
          TO: ${{ secrets.TO }}
          AUTH: ${{ secrets.AUTH }}
        run: python main.py
